import Table from "./_components/table";
// import Breadcrumb from "@/components/Breadcrumbs/Breadcrumb";
// import DefaultLayout from "@/components/Layouts/DefaultLayout";
import { db } from "../lib/db";

export const metadata = {
  title:
    "Cineng Galungan Gift - Generated by cineng slebeww~",
  description: "Generated by cineng slebeww~",
  
};

export default async function UserPage() {
  const spins = await db.spin.findMany({
    orderBy: {
      created_at: "asc",
    },
  });
  

  return (

      <Table spins={spins} />
  );
}
